// wolfCI command-line client protocol. Distinct from
// AgentService so the cert-CN -> matrix permission check can
// gate human callers separately from build agents.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: api/v1/cli/cli.proto

package cliv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CLIService_ListJobs_FullMethodName  = "/wolfci.v1.cli.CLIService/ListJobs"
	CLIService_ListNodes_FullMethodName = "/wolfci.v1.cli.CLIService/ListNodes"
)

// CLIServiceClient is the client API for CLIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CLIServiceClient interface {
	// ListJobs returns every job defined on disk.
	ListJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// ListNodes returns every agent the server knows about,
	// both Register'd (visible) and currently connected.
	ListNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type cLIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCLIServiceClient(cc grpc.ClientConnInterface) CLIServiceClient {
	return &cLIServiceClient{cc}
}

func (c *cLIServiceClient) ListJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, CLIService_ListJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIServiceClient) ListNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, CLIService_ListNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CLIServiceServer is the server API for CLIService service.
// All implementations must embed UnimplementedCLIServiceServer
// for forward compatibility
type CLIServiceServer interface {
	// ListJobs returns every job defined on disk.
	ListJobs(context.Context, *Empty) (*ListJobsResponse, error)
	// ListNodes returns every agent the server knows about,
	// both Register'd (visible) and currently connected.
	ListNodes(context.Context, *Empty) (*ListNodesResponse, error)
	mustEmbedUnimplementedCLIServiceServer()
}

// UnimplementedCLIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCLIServiceServer struct {
}

func (UnimplementedCLIServiceServer) ListJobs(context.Context, *Empty) (*ListJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedCLIServiceServer) ListNodes(context.Context, *Empty) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedCLIServiceServer) mustEmbedUnimplementedCLIServiceServer() {}

// UnsafeCLIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CLIServiceServer will
// result in compilation errors.
type UnsafeCLIServiceServer interface {
	mustEmbedUnimplementedCLIServiceServer()
}

func RegisterCLIServiceServer(s grpc.ServiceRegistrar, srv CLIServiceServer) {
	s.RegisterService(&CLIService_ServiceDesc, srv)
}

func _CLIService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServiceServer).ListJobs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLIService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServiceServer).ListNodes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CLIService_ServiceDesc is the grpc.ServiceDesc for CLIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CLIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wolfci.v1.cli.CLIService",
	HandlerType: (*CLIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListJobs",
			Handler:    _CLIService_ListJobs_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _CLIService_ListNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/cli/cli.proto",
}
