// wolfCI plugin protocol. Plugins are out-of-process gRPC
// servers loaded by the wolfCI server via hashicorp/go-plugin.
// Hand-edit this file; the matching .pb.go and _grpc.pb.go
// files are generated by scripts/gen-proto.sh.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: api/v1/plugin/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WolfCIPlugin_OnBuildComplete_FullMethodName = "/wolfci.v1.plugin.WolfCIPlugin/OnBuildComplete"
)

// WolfCIPluginClient is the client API for WolfCIPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WolfCIPluginClient interface {
	// OnBuildComplete fires after the server records a build's
	// final result. Plugins do whatever they like with the event:
	// send a notification, post to a chat service, update an
	// external dashboard. The server does not wait long for the
	// reply; plugins that need to do slow work should return
	// quickly and continue in their own goroutine.
	OnBuildComplete(ctx context.Context, in *BuildCompleteEvent, opts ...grpc.CallOption) (*Empty, error)
}

type wolfCIPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewWolfCIPluginClient(cc grpc.ClientConnInterface) WolfCIPluginClient {
	return &wolfCIPluginClient{cc}
}

func (c *wolfCIPluginClient) OnBuildComplete(ctx context.Context, in *BuildCompleteEvent, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, WolfCIPlugin_OnBuildComplete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WolfCIPluginServer is the server API for WolfCIPlugin service.
// All implementations must embed UnimplementedWolfCIPluginServer
// for forward compatibility
type WolfCIPluginServer interface {
	// OnBuildComplete fires after the server records a build's
	// final result. Plugins do whatever they like with the event:
	// send a notification, post to a chat service, update an
	// external dashboard. The server does not wait long for the
	// reply; plugins that need to do slow work should return
	// quickly and continue in their own goroutine.
	OnBuildComplete(context.Context, *BuildCompleteEvent) (*Empty, error)
	mustEmbedUnimplementedWolfCIPluginServer()
}

// UnimplementedWolfCIPluginServer must be embedded to have forward compatible implementations.
type UnimplementedWolfCIPluginServer struct {
}

func (UnimplementedWolfCIPluginServer) OnBuildComplete(context.Context, *BuildCompleteEvent) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnBuildComplete not implemented")
}
func (UnimplementedWolfCIPluginServer) mustEmbedUnimplementedWolfCIPluginServer() {}

// UnsafeWolfCIPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WolfCIPluginServer will
// result in compilation errors.
type UnsafeWolfCIPluginServer interface {
	mustEmbedUnimplementedWolfCIPluginServer()
}

func RegisterWolfCIPluginServer(s grpc.ServiceRegistrar, srv WolfCIPluginServer) {
	s.RegisterService(&WolfCIPlugin_ServiceDesc, srv)
}

func _WolfCIPlugin_OnBuildComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildCompleteEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WolfCIPluginServer).OnBuildComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WolfCIPlugin_OnBuildComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WolfCIPluginServer).OnBuildComplete(ctx, req.(*BuildCompleteEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// WolfCIPlugin_ServiceDesc is the grpc.ServiceDesc for WolfCIPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WolfCIPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wolfci.v1.plugin.WolfCIPlugin",
	HandlerType: (*WolfCIPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnBuildComplete",
			Handler:    _WolfCIPlugin_OnBuildComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/plugin/plugin.proto",
}
