// wolfCI plugin protocol. Plugins are out-of-process gRPC
// servers loaded by the wolfCI server via hashicorp/go-plugin.
// Hand-edit this file; the matching .pb.go and _grpc.pb.go
// files are generated by scripts/gen-proto.sh.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.34.1
// source: api/v1/plugin/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuildCompleteEvent is everything a plugin learns about a
// finished build.
type BuildCompleteEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName     string `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	BuildNumber int32  `protobuf:"varint,2,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	// status is one of "success", "failure", "cancelled", "error",
	// matching scheduler.Status.
	Status   string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ExitCode int32  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error    string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BuildCompleteEvent) Reset() {
	*x = BuildCompleteEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_plugin_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildCompleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCompleteEvent) ProtoMessage() {}

func (x *BuildCompleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCompleteEvent.ProtoReflect.Descriptor instead.
func (*BuildCompleteEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *BuildCompleteEvent) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *BuildCompleteEvent) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *BuildCompleteEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BuildCompleteEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *BuildCompleteEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_plugin_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_plugin_proto_rawDescGZIP(), []int{1}
}

var File_api_v1_plugin_plugin_proto protoreflect.FileDescriptor

var file_api_v1_plugin_plugin_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x77, 0x6f,
	0x6c, 0x66, 0x63, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x22, 0x9d,
	0x01, 0x0a, 0x12, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x60, 0x0a, 0x0c, 0x57, 0x6f, 0x6c, 0x66, 0x43,
	0x49, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x50, 0x0a, 0x0f, 0x4f, 0x6e, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x77, 0x6f, 0x6c,
	0x66, 0x63, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x1a, 0x17, 0x2e, 0x77, 0x6f, 0x6c, 0x66, 0x63, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x6c, 0x65, 0x62, 0x2d, 0x68, 0x69,
	0x6d, 0x65, 0x73, 0x2f, 0x77, 0x6f, 0x6c, 0x66, 0x43, 0x49, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x3b, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_plugin_plugin_proto_rawDescOnce sync.Once
	file_api_v1_plugin_plugin_proto_rawDescData = file_api_v1_plugin_plugin_proto_rawDesc
)

func file_api_v1_plugin_plugin_proto_rawDescGZIP() []byte {
	file_api_v1_plugin_plugin_proto_rawDescOnce.Do(func() {
		file_api_v1_plugin_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_plugin_plugin_proto_rawDescData)
	})
	return file_api_v1_plugin_plugin_proto_rawDescData
}

var file_api_v1_plugin_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_plugin_plugin_proto_goTypes = []interface{}{
	(*BuildCompleteEvent)(nil), // 0: wolfci.v1.plugin.BuildCompleteEvent
	(*Empty)(nil),              // 1: wolfci.v1.plugin.Empty
}
var file_api_v1_plugin_plugin_proto_depIdxs = []int32{
	0, // 0: wolfci.v1.plugin.WolfCIPlugin.OnBuildComplete:input_type -> wolfci.v1.plugin.BuildCompleteEvent
	1, // 1: wolfci.v1.plugin.WolfCIPlugin.OnBuildComplete:output_type -> wolfci.v1.plugin.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_plugin_plugin_proto_init() }
func file_api_v1_plugin_plugin_proto_init() {
	if File_api_v1_plugin_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_plugin_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildCompleteEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_plugin_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_plugin_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_plugin_plugin_proto_goTypes,
		DependencyIndexes: file_api_v1_plugin_plugin_proto_depIdxs,
		MessageInfos:      file_api_v1_plugin_plugin_proto_msgTypes,
	}.Build()
	File_api_v1_plugin_plugin_proto = out.File
	file_api_v1_plugin_plugin_proto_rawDesc = nil
	file_api_v1_plugin_plugin_proto_goTypes = nil
	file_api_v1_plugin_plugin_proto_depIdxs = nil
}
